### ISSUE TITLE
Unable to stream on Windows

### ISSUE THREAD

**Issue by sukiletxe** [rzane/dlnanow#1]
When using dlnanow on Windows, only `--help` returns some output. If I try to stream a file or a URL, I get no output and the streaming doesn't start. I can't give you more information to diagnose the problem, as the program exits even before finding devices.

**Comment by sukiletxe** [comment]
My computer couldn't find devices for unknown reasons, but apparently now it can. Closing.

**Comment by sukiletxe** [comment]
This is strange. When I closed the issue, i was testing with dlnacasts (using interactive mode (REPL)) and it worked. Now I'm testing with dlnanow and another similar module which also uses dlnacasts, and no players are found in either case. However, if I query `dlnacasts.players` in REPL, sometimes it detects them.

**Comment by sukiletxe** [comment]
Closing, as this is not specific to this program. The problem persists, but it happens when I test with other software too, so it must be something with my network or my computer.

**Comment by rzane** [comment]
I personally don't use Windows, so I'm unlikely to investigate. But, if you find a solution the problem, I'd be interested in hearing about it!
